version: '3.8'
services:
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
volumes:
    db_data:
