version: "3.8"

services:
    db:
        image: mysql:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - algafood-network

volumes:
    db_data:

networks:
    algafood-network:
        driver: bridge
