name: development

services:
    mysql:
        image: mysql:9
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - db_mysql:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db_mysql:
